/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MorganizeItApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MorganizeItWeb": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Notebooks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Notes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}