import type { WebSocket } from "ws";
import { Observable, of } from "rxjs";
import { ConnectionRegistry } from "../connection-registry";

/**
 * In-process registry used by the Express transport. ConnectionIds are
 * generated by the registry itself when a socket is registered, then handed
 * back to the caller so it can later deregister on close.
 *
 * The registry also exposes a typed lookup from connectionId back to the
 * underlying WebSocket so the LocalWsPublisher can call `socket.send`.
 */
export class InMemoryConnectionRegistry implements ConnectionRegistry {
  private byConnectionId = new Map<string, { userId: string; socket: WebSocket }>();
  private byUserId = new Map<string, Set<string>>();

  registerSocket(userId: string, socket: WebSocket): string {
    const connectionId = `local-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
    this.byConnectionId.set(connectionId, { userId, socket });
    let set = this.byUserId.get(userId);
    if (!set) {
      set = new Set();
      this.byUserId.set(userId, set);
    }
    set.add(connectionId);
    return connectionId;
  }

  add(): Observable<void> {
    // Express path uses registerSocket directly; this is here to satisfy the
    // ConnectionRegistry interface and is a no-op.
    return of(undefined);
  }

  remove(connectionId: string): Observable<void> {
    const entry = this.byConnectionId.get(connectionId);
    if (entry) {
      this.byConnectionId.delete(connectionId);
      const set = this.byUserId.get(entry.userId);
      if (set) {
        set.delete(connectionId);
        if (set.size === 0) this.byUserId.delete(entry.userId);
      }
    }
    return of(undefined);
  }

  findByUserIds(userIds: string[]): Observable<string[]> {
    const ids: string[] = [];
    for (const userId of userIds) {
      const set = this.byUserId.get(userId);
      if (set) for (const id of set) ids.push(id);
    }
    return of(ids);
  }

  getSocket(connectionId: string): WebSocket | undefined {
    return this.byConnectionId.get(connectionId)?.socket;
  }
}
